fullnameOverride: keep-admin

replicaCount: 1

image:
  repository: yeonjae0426/keep-admin
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# 실제 컨테이너 포트
containerPort: 8080

# Spring 환경변수
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: api.ip
    value: http://192.168.90.192:18000
  - name: TZ
    value: Asia/Seoul

# ingress는 추후 사용
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# CPU 노드에만 스케줄링
nodeSelector:
  node-role: cpu

tolerations: []

affinity: {}

resources: {}

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""
