fullnameOverride: keep-admin

replicaCount: 1

image:
  repository: yeonjae0426/keep-admin
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev

  - name: api.ip
    value: http://192.168.90.192:18000

  - name: admin.id
    value: admin

  - name: admin.password
    value: epa123!@#

  - name: spring.datasource.url
    value: "jdbc:log4jdbc:mysql://192.168.90.192:23306/epa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true"
  - name: spring.datasource.username
    value: "epa"
  - name: spring.datasource.password
    value: "epa#2025"
  - name: spring.datasource.driver-class-name
    value: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"

  - name: TZ
    value: Asia/Seoul

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

nodeSelector:
  node-role: cpu

tolerations: []

affinity: {}

resources: {}

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""
