fullnameOverride: keep-admin

replicaCount: 1

image:
  repository: yeonjae0426/keep-admin
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev

  - name: api.ip
    value: http://192.168.90.192:18000

  - name: admin.id
    value: admin

  - name: admin.password
    value: epa123!@#

  - name: TZ
    value: Asia/Seoul

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

nodeSelector:
  node-role: cpu

tolerations: []

affinity: {}

resources: {}

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""
