apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep-admin.fullname" . }}
  labels:
    {{- include "keep-admin.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "keep-admin.selectorLabels" . | nindent 4 }}
